base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.loginPage,name = 'loginPage'),
    path('logout/',views.logoutUser, name = 'logoutUser'),
    path('',views.home,name = 'home'),
    path('post/<slug:slug>/',views.post,name = 'post'),
    path('categories/<int:pk>/', views.categoryPosts, name = 'categories'),
    path('video-posts/',views.videoPosts, name = 'videoPosts'),
    path('video-post/<slug:slug>/',views.videoPost, name = 'videoPost'),
    path('audio-posts/',views.audioPostsView, name = 'audioPosts'),
    path('audio-post/<slug:slug>/',views.audioPost, name = 'audio'),
    path('contact-us/',views.contactView, name = 'contact'),
    
    
    #CRUD PATHS
    path('categories/add-category/', views.addCategoryView, name = 'add_category'),
    path('posts/add-post/', views.addPostView, name = 'add_post'),
    path('posts/delete-post/<slug:slug>/', views.deletePost, name = 'delete_post'),
    path('posts/update-post/<slug:slug>/',views.updatePost, name = 'update_post'),
    path('video-posts/add-video-post/',views.addVideoPost,name = 'add_video_post'),
    path('video-posts/update-video-post/<slug:slug>/',views.updateVideoPost, name = 'update_video_post'),
    path('video-posts/delete/<slug:slug>/', views.deleteVideoPost, name = 'delete_video_post'),
    path('audio-posts/add-audio-post/',views.addAudioView,name = 'add_audio_post'),
    path('audio-posts/update-audio-post/<slug:slug>/',views.updateAudioPost, name = 'update_audio_post'),
    path('audio-posts/delete/<slug:slug>/', views.deleteAudioPost, name = 'delete_audio_post'),
]

kobby/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

base/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from django.contrib.auth.models import User
from datetime import date, time, datetime
from cloudinary_storage.storage import VideoMediaCloudinaryStorage
from cloudinary_storage.validators import validate_video

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.name
    

    
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User,on_delete= models.CASCADE)
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to = 'images',default = 'defaults/kobyDrillsDotKom.png')
    body = RichTextUploadingField()
    date = models.DateField(auto_now_add=True)
    slug = models.SlugField(blank = True, null = True)
    
    
    def __str__(self):
        return self.title
    
    def save(self, *args,**kwargs):
        
        if self.slug == None:
            slug = slugify(self.title)
            
            slug_exist = Post.objects.filter(slug = slug).exists()
            
            count = 0
            while slug_exist:
                count += 1
                slug = slugify(self.title) + '-' + str(count)
                slug_exist = Post.objects.filter(slug = slug).exists()
                
            self.slug = slug
            
        
        super().save(*args,**kwargs)
        
    @property
    def get_body_length(self):
        length = len(self.body)
        return length
    
    
class VideoPost(models.Model):
    caption = models.CharField(max_length=100)
    video = models.FileField(upload_to='videos/%y/',storage=VideoMediaCloudinaryStorage(),validators=[validate_video])
    thumbnail = models.ImageField(null = True, blank = True, default = 'defaults/kobyDrillsDotKom.png', upload_to = 'videos/%y/thumbnails')
    body = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)
    category = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True, blank=True, null= True)
    slug = models.SlugField(blank = True, null = True)
    
    def __str__(self):
        return self.caption
    
    def save(self,*args,**kwargs):
        
        if self.slug == None:
            slug = slugify(self.caption)
            
            count = 0
            slug_exist = VideoPost.objects.filter(slug = slug).exists()
            
            while slug_exist:
                slug = slugify(self.caption) + '-' + count
                count += 1
                
                slug_exist = VideoPost.objects.filter(slug = slug).exists()

            self.slug = slug
            
        super().save(*args,**kwargs)
        
    @property
    def get_body_length(self):
        length = len(self.body)
        return length
    
    
class PostComment(models.Model):
    post= models.ForeignKey(Post,on_delete = models.CASCADE, related_name='comments')
    name = models.CharField(max_length=200)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.post.title} - {self.name}'


class VideoPostComment(models.Model):
    video = models.ForeignKey(VideoPost,on_delete = models.CASCADE, related_name='video_comments')
    name = models.CharField(max_length=200)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.video.caption} - {self.name}'
    
class AudioPost(models.Model):
    audio = models.FileField(upload_to='audio/%y/',storage=VideoMediaCloudinaryStorage(), validators = [validate_video])
    caption = models.CharField(max_length=100)
    thumbnail = models.ImageField(null = True, blank = True, default = 'defaults/kobyDrillsDotKom.png', upload_to = 'audios/%y/thumbnails')
    body = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)
    category = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True, blank=True, null= True)
    slug = models.SlugField(blank = True, null = True)
    
    def __str__(self):
        return f'{self.caption}'
     
    def save(self,*args,**kwargs):
        
        if self.slug == None:
            slug = slugify(self.caption)
            
            count = 0
            slug_exist = VideoPost.objects.filter(slug = slug).exists()
            
            while slug_exist:
                slug = slugify(self.caption) + '-' + count
                count += 1
                
                slug_exist = VideoPost.objects.filter(slug = slug).exists()

            self.slug = slug
            
        super().save(*args,**kwargs)
        
    @property
    def get_body_length(self):
        length = len(self.body)
        return length
    

class AudioPostComment(models.Model):
    audio = models.ForeignKey(AudioPost,on_delete = models.CASCADE, related_name='audio_comments')
    name = models.CharField(max_length=200)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.audio.caption} - {self.name}'

base/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import *

# Create your views here.
# -------------------------------------------------------------------------------------
#                         LOGIN PAGE
# -------------------------------------------------------------------------------------                        
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messages.info(request, 'Incorrect Username or password (They are case sensitive)')
        
    return render(request,'login.htm')


# -------------------------------------------------------------------------------------
#                         LOGOUT
# -------------------------------------------------------------------------------------
def logoutUser(request):
    logout(request)
    return redirect('loginPage')


# -------------------------------------------------------------------------------------
#                         HOME PAGE
# -------------------------------------------------------------------------------------
def home(request):
    posts = Post.objects.all()
    categories = Category.objects.all()
    myFilter = PostFilter(request.GET,queryset = posts)
    posts = myFilter.qs
    
    page =  request.GET.get('page')
    paginator = Paginator(posts,20)
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        
    
    
    context = {
        'posts': posts,
        'categories':categories,
        'myFilter':myFilter
    }
    
    return render(request, 'index.htm', context)



# -------------------------------------------------------------------------------------
#                         POST VIEW
# -------------------------------------------------------------------------------------
def post(request,slug):
    categories = Category.objects.all()
    post = Post.objects.get(slug = slug)
    
    commentForm = PostCommentForm()
    
    if request.method == 'POST':
        commentForm = PostCommentForm(request.POST)
        if commentForm.is_valid():
            commentForm.save()
        return redirect('home')
        
    
    context = {
        'categories':categories,
        'post':post,
        'commentForm': commentForm
        
    }
    return render(request, 'post.htm',context)



# -------------------------------------------------------------------------------------
#                         VIDEO POSTS VIEW
# -------------------------------------------------------------------------------------
def videoPosts(request):
    categories = Category.objects.all()
    videos = VideoPost.objects.all()
    myFilter = VideoFilter(request.GET,queryset = videos)
    videos = myFilter.qs
    
    page = request.GET.get('page')
    paginator = Paginator(videos,20)
    
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)
    
    context = {
        'videos':videos,
        'myFilter':myFilter,
        'categories':categories,
    }
    
    return render(request,'video-posts.htm',context)


# -------------------------------------------------------------------------------------
#                         VIDEO POST VIEW
# -------------------------------------------------------------------------------------
def videoPost(request,slug):
    video = VideoPost.objects.get(slug = slug)
    
    commentForm = VideoPostCommentForm()
    
    if request.method == 'POST':
        commentForm = VideoPostCommentForm(request.POST)
        if commentForm.is_valid():
            commentForm.save()
        return redirect('videoPosts')
            
    
    context = {
        'video':video,
        'commentForm':commentForm,
    }
    return render(request,'video-post.htm',context)

# -------------------------------------------------------------------------------------
#                         AUDIO POSTS VIEW
# -------------------------------------------------------------------------------------
def audioPostsView(request):
    categories = Category.objects.all()
    audios = AudioPost.objects.all()
    
    myFilter = VideoFilter(request.GET,queryset = audios)
    audios = myFilter.qs
    
    page = request.GET.get('page')
    paginator = Paginator(audios,20)
    
    try:
        audios = paginator.page(page)
    except PageNotAnInteger:
        audios = paginator.page(1)
    except EmptyPage:
        audios = paginator.page(paginator.num_pages)
    
    
    context = {
        'audios':audios,
        'myFilter':myFilter,
        'categories':categories
    }
    
    return render(request,'audio-posts.htm',context)

# -------------------------------------------------------------------------------------
#                         AUDIO POST VIEW
# -------------------------------------------------------------------------------------

def audioPost(request,slug):
    audio = AudioPost.objects.get(slug = slug)
    categories = Category.objects.all()
    commentForm = AudioPostCommentForm()
    
    if request.method == 'POST':
        commentForm = AudioPostCommentForm(request.POST)
        if commentForm.is_valid():
            commentForm.save()
        return redirect('audioPosts')
            
    
    context = {
        'audio':audio,
        'commentForm':commentForm,
        'categories':categories
    }
    return render(request,'audio-post.htm',context)


# -------------------------------------------------------------------------------------
#                         CATEGORIES VIEW
# -------------------------------------------------------------------------------------
def categoryPosts(request,pk):
    category_posts = Post.objects.filter(category = pk)
    category_video_posts = VideoPost.objects.filter(category = pk)
    category_audio_posts = AudioPost.objects.filter(category = pk)
    
    cats = Category.objects.get(id = pk)


    categories = Category.objects.all()

    page =  request.GET.get('page')
    paginator = Paginator(category_posts,20)
    
    try:
        category_posts = paginator.page(page)
    except PageNotAnInteger:
        category_posts = paginator.page(1)
    except EmptyPage:
        category_posts = paginator.page(paginator.num_pages)

    context= {
        'cats': cats,
        'category_posts': category_posts,
        'category_video_posts':category_video_posts,
        'category_audio_posts':category_audio_posts,
        'categories': categories
    }
    
    return render(request,'category1.htm',context)


# -------------------------------------------------------------------------------------
#                                   CONTACT PAGE
# -------------------------------------------------------------------------------------
def contactView(request):
    return render(request,'contact.htm')


# -------------------------------------------------------------------------------------
#                                   CRUDS
# -------------------------------------------------------------------------------------


# -------------------------------------------------------------------------------------
#                        ADD VIDEO POST VIEW
# -------------------------------------------------------------------------------------
def addVideoPost(request):
    form = AddVideoPostForm()
    categories = Category.objects.all()
    
    if request.method == 'POST':
        form = AddVideoPostForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('videoPosts')

    context = {
        'categories':categories,
        'videoForm':form
    }

    return render(request,'forms/add-video-post.htm',context)


# -------------------------------------------------------------------------------------
#                        UPDATE VIDEO
# -------------------------------------------------------------------------------------
def updateVideoPost(request,slug):
    video= VideoPost.objects.get(slug = slug)
    
    form = AddVideoPostForm(instance = video)
    
    if request.method == 'POST':
        form = AddVideoPostForm(request.POST,instance = video)
        if form.is_valid():
            form.save()
        return redirect('home')
    
    context = {
        'postForm':form
    }
    return render(request,'forms/update-post.htm',context)    

# -------------------------------------------------------------------------------------
#                         DELETE VIDEO VIEW
# -------------------------------------------------------------------------------------
@login_required(login_url='loginPage')
def deleteVideoPost(request,slug):
    video = VideoPost.objects.get(slug = slug)
    video.delete()
    return redirect('home')



# -------------------------------------------------------------------------------------
#                        ADD AUDIO VIEW
# -------------------------------------------------------------------------------------
@login_required(login_url='loginPage')
def addAudioView(request):
    categories = Category.objects.all()
    form = AddAudioForm()
    
    if request.method == 'POST':
        form = AddAudioForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('home') 
        
    context = {
        'categories':categories,

base/templates/forms/add-audio.htm
{% extends 'main.htm' %}
{% load static %}
{% block title %} Add Audio Post {% endblock %}
{% block content %}

    <style>
        ul{
            list-style: none;
        }
        #id_title{
            width: 100%;
        }
        #id_author,#id_body,#id_caption{
            width: 100%;
        }
        .errorlist{
            color: red;
        }
    </style>
    

        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <section class="column large-full entry format-standard">

                    
                    <h3 class="h2">Add Audio</h3>
        
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{audioForm.media}}
                        {{audioForm}}
                        <input type="submit" class="btn--primary full-width" value="Add Audio">
                    </form>

                </section>


                
            </main>

        </div> <!-- end s-content -->

        <script>
            var name = '{{user.id}}';
            document.getElementById('id_author').value = name;
        </script>

{% endblock %}

base/templates/forms/add-category.htm
{% extends 'main.htm' %}
{% load static %}
{% block title %} Add Category {% endblock %}
{% block content %}

    <style>
        ul{
            list-style: none;
        }
        #id_name{
            width: 100%;
        }
        
        .errorlist{
            color: red;
        }
    </style>
    

        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <section class="column large-full entry format-standard">

                    
                    <h3 class="h2">Add Category</h3>
        
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{categoryForm.media}}
                        {{categoryForm}}
                        <input type="submit" class="btn--primary full-width" value="Add Category">
                    </form>

                </section>


                
            </main>

        </div> <!-- end s-content -->


{% endblock %}

base/templates/forms/add-post.htm
{% extends 'main.htm' %}
{% load static %}
{% block title %} Add Standard Post {% endblock %}
{% block content %}

    <style>
        ul{
            list-style: none;
        }
        #id_title{
            width: 100%;
        }
        #id_author,#id_body{
            width: 100%;
        }
        .errorlist{
            color: red;
        }
    </style>
    

        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <section class="column large-full entry format-standard">

                    
                    <h3 class="h2">Add Post</h3>
        
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{postForm.media}}
                        {{postForm}}
                        <input type="submit" class="btn--primary full-width" value="Add Post">
                    </form>

                </section>


                
            </main>

        </div> <!-- end s-content -->


        <script>
            var name = '{{user.id}}';
            document.getElementById('id_author').value = name;
        </script>
{% endblock %}

base/templates/forms/add-video-post.htm
{% extends 'main.htm' %}
{% load static %}
{% block title %} Add Video Post {% endblock %}
{% block content %}

    <style>
        ul{
            list-style: none;
        }
        #id_caption{
            width: 100%;
        }
        #id_author,#id_body{
            width: 100%;
        }
        .errorlist{
            color: red;
        }
    </style>
    

        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <section class="column large-full entry format-standard">

                    
                    <h3 class="h2">Add Video Post</h3>
        
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{videoForm.media}}
                        {{videoForm}}
                        <input type="submit" class="btn--primary full-width" value="Add Video Post">
                    </form>

                </section>


                
            </main>

        </div> <!-- end s-content -->

        <script>
            var name = '{{user.id}}';
            document.getElementById('id_author').value = name;
        </script>

{% endblock %}

base/templates/forms/update-post.htm
{% extends 'main.htm' %}
{% load static %}
{% block title %} Update Post {% endblock %}
{% block content %}

    <style>
        ul{
            list-style: none;
        }
        #id_title{
            width: 100%;
        }
        #id_author,#id_body,#id_caption{
            width: 100%;
        }
        .errorlist{
            color: red;
        }
    </style>
    

        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <section class="column large-full entry format-standard">

                    
                    <h3 class="h2">Update Post</h3>
        
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{postForm.media}}
                        {{postForm}}
                        <input type="submit" class="btn--primary full-width" value="Save Changes">
                    </form>

                </section>


                
            </main>

        </div> <!-- end s-content -->


{% endblock %}