base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.loginPage,name = 'loginPage'),
    path('logout/',views.logoutUser, name = 'logoutUser'),
    path('',views.home,name = 'home'),
    path('post/<slug:slug>/',views.post,name = 'post'),
    path('categories/<int:pk>/', views.categoryPosts, name = 'categories'),
    path('video-posts/',views.videoPosts, name = 'videoPosts'),
    path('video-post/<slug:slug>/',views.videoPost, name = 'videoPost'),
    path('audio-posts/',views.audioPostsView, name = 'audioPosts'),
    path('audio-post/<slug:slug>/',views.audioPost, name = 'audio'),
    path('contact-us/',views.contactView, name = 'contact'),
    
    
    #CRUD PATHS
    path('categories/add-category/', views.addCategoryView, name = 'add_category'),
    path('posts/add-post/', views.addPostView, name = 'add_post'),
    path('posts/delete-post/<slug:slug>/', views.deletePost, name = 'delete_post'),
    path('posts/update-post/<slug:slug>/',views.updatePost, name = 'update_post'),
    path('video-posts/add-video-post/',views.addVideoPost,name = 'add_video_post'),
    path('video-posts/update-video-post/<slug:slug>/',views.updateVideoPost, name = 'update_video_post'),
    path('video-posts/delete/<slug:slug>/', views.deleteVideoPost, name = 'delete_video_post'),
    path('audio-posts/add-audio-post/',views.addAudioView,name = 'add_audio_post'),
    path('audio-posts/update-audio-post/<slug:slug>/',views.updateAudioPost, name = 'update_audio_post'),
    path('audio-posts/delete/<slug:slug>/', views.deleteAudioPost, name = 'delete_audio_post'),
]

kobby/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

base/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from django.contrib.auth.models import User
from datetime import date, time, datetime
from cloudinary_storage.storage import VideoMediaCloudinaryStorage
from cloudinary_storage.validators import validate_video

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.name
    

    
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User,on_delete= models.CASCADE)
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to = 'images',default = 'defaults/kobyDrillsDotKom.png')
    body = RichTextUploadingField()
    date = models.DateField(auto_now_add=True)
    slug = models.SlugField(blank = True, null = True)
    
    
    def __str__(self):
        return self.title
    
    def save(self, *args,**kwargs):
        
        if self.slug == None:
            slug = slugify(self.title)
            
            slug_exist = Post.objects.filter(slug = slug).exists()
            
            count = 0
            while slug_exist:
                count += 1
                slug = slugify(self.title) + '-' + str(count)
                slug_exist = Post.objects.filter(slug = slug).exists()
                
            self.slug = slug
            
        
        super().save(*args,**kwargs)
        
    @property
    def get_body_length(self):
        length = len(self.body)
        return length
    
    
class VideoPost(models.Model):
    caption = models.CharField(max_length=100)
    video = models.FileField(upload_to='videos/%y/',storage=VideoMediaCloudinaryStorage(),validators=[validate_video])
    thumbnail = models.ImageField(null = True, blank = True, default = 'defaults/kobyDrillsDotKom.png', upload_to = 'videos/%y/thumbnails')
    body = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)
    category = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True, blank=True, null= True)
    slug = models.SlugField(blank = True, null = True)
    
    def __str__(self):
        return self.caption
    
    def save(self,*args,**kwargs):
        
        if self.slug == None:
            slug = slugify(self.caption)
            
            count = 0
            slug_exist = VideoPost.objects.filter(slug = slug).exists()
            
            while slug_exist:
                slug = slugify(self.caption) + '-' + count
                count += 1
                
                slug_exist = VideoPost.objects.filter(slug = slug).exists()

            self.slug = slug
            
        super().save(*args,**kwargs)
        
    @property
    def get_body_length(self):
        length = len(self.body)
        return length
    
    
class PostComment(models.Model):
    post= models.ForeignKey(Post,on_delete = models.CASCADE, related_name='comments')
    name = models.CharField(max_length=200)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.post.title} - {self.name}'


class VideoPostComment(models.Model):
    video = models.ForeignKey(VideoPost,on_delete = models.CASCADE, related_name='video_comments')
    name = models.CharField(max_length=200)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.video.caption} - {self.name}'
    
class AudioPost(models.Model):
    audio = models.FileField(upload_to='audio/%y/',storage=VideoMediaCloudinaryStorage(), validators = [validate_video])
    caption = models.CharField(max_length=100)
    thumbnail = models.ImageField(null = True, blank = True, default = 'defaults/kobyDrillsDotKom.png', upload_to = 'audios/%y/thumbnails')
    body = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)
    category = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True, blank=True, null= True)
    slug = models.SlugField(blank = True, null = True)
    
    def __str__(self):
        return f'{self.caption}'
     
    def save(self,*args,**kwargs):
        
        if self.slug == None:
            slug = slugify(self.caption)
            
            count = 0
            slug_exist = VideoPost.objects.filter(slug = slug).exists()
            
            while slug_exist:
                slug = slugify(self.caption) + '-' + count
                count += 1
                
                slug_exist = VideoPost.objects.filter(slug = slug).exists()

            self.slug = slug
            
        super().save(*args,**kwargs)
        
    @property
    def get_body_length(self):
        length = len(self.body)
        return length
    

class AudioPostComment(models.Model):
    audio = models.ForeignKey(AudioPost,on_delete = models.CASCADE, related_name='audio_comments')
    name = models.CharField(max_length=200)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.audio.caption} - {self.name}'

base/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import *

# Create your views here.
# -------------------------------------------------------------------------------------
#                         LOGIN PAGE
# -------------------------------------------------------------------------------------                        
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messages.info(request, 'Incorrect Username or password (They are case sensitive)')
        
    return render(request,'login.htm')


# -------------------------------------------------------------------------------------
#                         LOGOUT
# -------------------------------------------------------------------------------------
def logoutUser(request):
    logout(request)
    return redirect('loginPage')


# -------------------------------------------------------------------------------------
#                         HOME PAGE
# -------------------------------------------------------------------------------------
def home(request):
    posts = Post.objects.all()
    categories = Category.objects.all()
    myFilter = PostFilter(request.GET,queryset = posts)
    posts = myFilter.qs
    
    page =  request.GET.get('page')
    paginator = Paginator(posts,20)
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        
    
    
    context = {
        'posts': posts,
        'categories':categories,
        'myFilter':myFilter
    }
    
    return render(request, 'index.htm', context)



# -------------------------------------------------------------------------------------
#                         POST VIEW
# -------------------------------------------------------------------------------------
def post(request,slug):
    categories = Category.objects.all()
    post = Post.objects.get(slug = slug)
    
    commentForm = PostCommentForm()
    
    if request.method == 'POST':
        commentForm = PostCommentForm(request.POST)
        if commentForm.is_valid():
            commentForm.save()
        return redirect('home')
        
    
    context = {
        'categories':categories,
        'post':post,
        'commentForm': commentForm
        
    }
    return render(request, 'post.htm',context)



# -------------------------------------------------------------------------------------
#                         VIDEO POSTS VIEW
# -------------------------------------------------------------------------------------
def videoPosts(request):
    categories = Category.objects.all()
    videos = VideoPost.objects.all()
    myFilter = VideoFilter(request.GET,queryset = videos)
    videos = myFilter.qs
    
    page = request.GET.get('page')
    paginator = Paginator(videos,20)
    
    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)
    
    context = {
        'videos':videos,
        'myFilter':myFilter,
        'categories':categories,
    }
    
    return render(request,'video-posts.htm',context)


# -------------------------------------------------------------------------------------
#                         VIDEO POST VIEW
# -------------------------------------------------------------------------------------
def videoPost(request,slug):
    video = VideoPost.objects.get(slug = slug)
    
    commentForm = VideoPostCommentForm()
    
    if request.method == 'POST':
        commentForm = VideoPostCommentForm(request.POST)
        if commentForm.is_valid():
            commentForm.save()
        return redirect('videoPosts')
            
    
    context = {
        'video':video,
        'commentForm':commentForm,
    }
    return render(request,'video-post.htm',context)

# -------------------------------------------------------------------------------------
#                         AUDIO POSTS VIEW
# -------------------------------------------------------------------------------------
def audioPostsView(request):
    categories = Category.objects.all()
    audios = AudioPost.objects.all()
    
    myFilter = VideoFilter(request.GET,queryset = audios)
    audios = myFilter.qs
    
    page = request.GET.get('page')
    paginator = Paginator(audios,20)
    
    try:
        audios = paginator.page(page)
    except PageNotAnInteger:
        audios = paginator.page(1)
    except EmptyPage:
        audios = paginator.page(paginator.num_pages)
    
    
    context = {
        'audios':audios,
        'myFilter':myFilter,
        'categories':categories
    }
    
    return render(request,'audio-posts.htm',context)

# -------------------------------------------------------------------------------------
#                         AUDIO POST VIEW
# -------------------------------------------------------------------------------------

def audioPost(request,slug):
    audio = AudioPost.objects.get(slug = slug)
    categories = Category.objects.all()
    commentForm = AudioPostCommentForm()
    
    if request.method == 'POST':
        commentForm = AudioPostCommentForm(request.POST)
        if commentForm.is_valid():
            commentForm.save()
        return redirect('audioPosts')
            
    
    context = {
        'audio':audio,
        'commentForm':commentForm,
        'categories':categories
    }
    return render(request,'audio-post.htm',context)


# -------------------------------------------------------------------------------------
#                         CATEGORIES VIEW
# -------------------------------------------------------------------------------------
def categoryPosts(request,pk):
    category_posts = Post.objects.filter(category = pk)
    category_video_posts = VideoPost.objects.filter(category = pk)
    category_audio_posts = AudioPost.objects.filter(category = pk)
    
    cats = Category.objects.get(id = pk)


    categories = Category.objects.all()

    page =  request.GET.get('page')
    paginator = Paginator(category_posts,20)
    
    try:
        category_posts = paginator.page(page)
    except PageNotAnInteger:
        category_posts = paginator.page(1)
    except EmptyPage:
        category_posts = paginator.page(paginator.num_pages)

    context= {
        'cats': cats,
        'category_posts': category_posts,
        'category_video_posts':category_video_posts,
        'category_audio_posts':category_audio_posts,
        'categories': categories
    }
    
    return render(request,'category1.htm',context)


# -------------------------------------------------------------------------------------
#                                   CONTACT PAGE
# -------------------------------------------------------------------------------------
def contactView(request):
    return render(request,'contact.htm')


# -------------------------------------------------------------------------------------
#                                   CRUDS
# -------------------------------------------------------------------------------------


# -------------------------------------------------------------------------------------
#                        ADD VIDEO POST VIEW
# -------------------------------------------------------------------------------------
def addVideoPost(request):
    form = AddVideoPostForm()
    categories = Category.objects.all()
    
    if request.method == 'POST':
        form = AddVideoPostForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('videoPosts')

    context = {
        'categories':categories,
        'videoForm':form
    }

    return render(request,'forms/add-video-post.htm',context)


# -------------------------------------------------------------------------------------
#                        UPDATE VIDEO
# -------------------------------------------------------------------------------------
def updateVideoPost(request,slug):
    video= VideoPost.objects.get(slug = slug)
    
    form = AddVideoPostForm(instance = video)
    
    if request.method == 'POST':
        form = AddVideoPostForm(request.POST,instance = video)
        if form.is_valid():
            form.save()
        return redirect('home')
    
    context = {
        'postForm':form
    }
    return render(request,'forms/update-post.htm',context)    

# -------------------------------------------------------------------------------------
#                         DELETE VIDEO VIEW
# -------------------------------------------------------------------------------------
@login_required(login_url='loginPage')
def deleteVideoPost(request,slug):
    video = VideoPost.objects.get(slug = slug)
    video.delete()
    return redirect('home')



# -------------------------------------------------------------------------------------
#                        ADD AUDIO VIEW
# -------------------------------------------------------------------------------------
@login_required(login_url='loginPage')
def addAudioView(request):
    categories = Category.objects.all()
    form = AddAudioForm()
    
    if request.method == 'POST':
        form = AddAudioForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('home') 
        
    context = {
        'categories':categories,

base/templates/audio-post.htm
{% extends 'main.htm' %}
{% load static %}
{% block title %} {{audio}} {% endblock %}

{% block content %}


<style>
    #id_post,#id_name,#id_comment{
        width: 100%;
    }
    
</style>


<div class="s-content content">
    <main class="row content__page">

        <article class="column large-full entry format-audio">

            <div class="media-wrap entry__media">
                <img src="{{ audio.thumbnail.url }}" style="width: 100%; height: 70%;"  alt="">
            </div>

            <div class="content__page-header entry__header">
                <h1 class="display-1 entry__title">
                {{audio.caption}}
                </h1>
                <ul class="entry__header-meta">
                    <li class="author">By <a href="#0">{{audio.author}}</a></li>
                    <li class="date">{{audio.date}}</li>
                    <li class="cat-links">
                        {% for category in audio.category.all %}
                        <a href="{% url 'categories' category.id %}">{{category}}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div> <!-- end entry__header -->

            <div class="entry__content">

                <audio controls style="width: 100%;">
                    <source src="{{audio.audio.url}}" type="audio/ogg">
                    <source src="{{audio.audio.url}}" type="audio/mpeg">
                  Your browser does not support the audio element.
                </audio>

                <p class="lead drop-cap">
               {{audio.body|safe}}
                </p>

               


        <div class="comments-wrap" style="    padding-left: 20px;
        padding-right: 20px;">

            <div id="comments" class="column large-12">

                <h3 class="h2">Comments</h3>

                <!-- COMMENT LIST -->
                <ol class="commentlist">
                    {% for comment in audio.audio_comments.all %}
                    <li class="depth-1 comment" style="background-color: #eaeaea; padding: 10px 20px; margin: 5px auto;">

                        <div class="comment__content">

                            <div class="comment__info">
                                <div class="comment__author" style="text-transform: uppercase;">{{comment.name}}</div>

                                <div class="comment__meta">
                                    <div class="comment__time">{{comment.date}}</div>
                                </div>
                            </div>

                            <div class="comment__text">
                            <p>
                                {{comment.comment}}
                            </p>
                            </div>

                        </div>

                    </li> <!-- end comment level 1 -->
                    {% empty %}
                        <h2 style="text-align:center; color: brown;" >No Comments</h2>
                    {% endfor %}
                    

                </ol>
                <!-- END commentlist -->


            </div> <!-- end comments -->
    
    
            <div class="column large-12 comment-respond">

                <!-- START respond -->
                <div id="respond">
    
                    <h3 class="h2">Add Comment</h3>
    
                    <form name="contactForm" id="commentForm" method="post" action="" autocomplete="off">
                        {% csrf_token %}
                        {{ commentForm.media }}
                        {{ commentForm }}
                        <input type="submit" class="btn--primary full-width" value="Add Comment">
                    </form> <!-- end form -->
    
                </div>
                <!-- END respond-->
    
            </div> <!-- end comment-respond -->
    
        </div> <!-- end comments-wrap -->
    </main>

</div> <!-- end s-content -->


<script>
    var name = '{{audio.id}}';
    document.getElementById('id_audio').value = name;
</script>
{% endblock %}

base/templates/category.htm
{{cats}}
{% for post in category_posts %}

<h1>
    {{post.title}}
</h1>

{% endfor %}

base/templates/post.htm
{% extends 'main.htm' %}
{% load static %}
{% block title %} {{post}} {% endblock %}
{% block content %}


<style>
    #id_post,#id_name,#id_comment{
        width: 100%;
    }
    
</style>
        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <article class="column large-full entry format-standard">

                    <div class="media-wrap entry__media">
                        <div class="entry__post-thumb">
                            <img style="width: 100%;" src="{{post.image.url}}" 
                                 srcset="{{post.image.url}} 2000w, 
                                 {{post.image.url}} 1000w, 
                                 {{post.image.url}} 500w" sizes="(max-width: 2000px) 100vw, 2000px" alt="">
                        </div>
                    </div>

                    <div class="content__page-header entry__header">
                        <h1 class="display-1 entry__title">
                        {{post.title}}
                        </h1>
                        <ul class="entry__header-meta">
                            <li class="author">By <a href="#0" style="text-transform: uppercase;">{{post.author}}</a></li>
                            <li class="date">{{post.date}}</li>
                            <li class="cat-links">
                                {% for category in post.category.all %}
                                
                                <a href="{% url 'categories' category.id %}" style="text-transform: uppercase;">{{category}}</a>
                                
                                {% endfor %}
                            </li>
                        </ul>
                    </div> <!-- end entry__header -->

                    <div class="entry__content">

                        <p class="lead drop-cap">
                        {{ post.body|safe }}
                        </p>

                    </div> <!-- end entry content -->
                    
                </article> <!-- end column large-full entry-->


                <div class="comments-wrap" style="width: 100%; padding-left: 20px;
                padding-right: 20px;">

                    <div id="comments" class="column large-12">

                        <h3 class="h2">Comments</h3>
        
                        <!-- START commentlist -->
                        <ol class="commentlist">
                            {% for comment in post.comments.all %}
                            <li class="depth-1 comment" style="background-color: #eaeaea; padding: 10px 20px; margin: 5px auto;">
        
                                <div class="comment__content">
        
                                    <div class="comment__info">
                                        <div class="comment__author" style="text-transform: uppercase;">{{comment.name}}</div>
        
                                        <div class="comment__meta">
                                            <div class="comment__time">{{comment.date}}</div>
                                        </div>
                                    </div>
        
                                    <div class="comment__text">
                                    <p>
                                        {{comment.comment}}
                                    </p>
                                    </div>
        
                                </div>
        
                            </li> <!-- end comment level 1 -->
                            {% empty %}
                                <h2 style="text-align:center; color: brown;" >No Comments</h2>
                            {% endfor %}
                            
        
                        </ol>
                        <!-- END commentlist -->

                    </div> <!-- end comments -->

                    <div class="column large-12 comment-respond">

                        <!-- START respond -->
                        <div id="respond">
            
                            <h3 class="h2">Add Comment</h3>
            
                            <form name="contactForm" id="commentForm" method="post" action="" autocomplete="off">
                                {% csrf_token %}
                                {{ commentForm.media }}
                                {{ commentForm }}
                                <input type="submit" class="btn--primary full-width" value="Add Comment">
                            </form> <!-- end form -->
            
                        </div>
                        <!-- END respond-->
            
                    </div> <!-- end comment-respond -->
            
                </div> <!-- end comments-wrap -->
            </main>

        </div> <!-- end s-content -->


        <script>
            var name = '{{post.id}}';
            document.getElementById('id_post').value = name;
        </script>
{% endblock %}

base/templates/video-post.htm
{% extends 'main.htm' %} 
{% load static %}  
{% block title %} {{video.caption}} {% endblock %}
{% block content %}


<style>
    #id_post,#id_name,#id_comment{
        width: 100%;
    }
    
</style>

<div class="s-content content">
    <main class="row content__page">
        
        
        <article class="column large-full entry format-video">

            <div class="media-wrap entry__media">
                <div class="video-container">
                    <video width="640" height="360" controls>
                        <source src="{{video.video.url}}" type="video/mp4">
                        <source src="{{video.video.url}}" type="video/ogg">
                      Your browser does not support the video tag.
                      </video>
                </div>
            </div>

            <div class="content__page-header entry__header">
                <h1 class="display-1 entry__title">
                {{video.caption}}
                </h1>
                <ul class="entry__header-meta">
                    <li class="author">By <a href="#0">{{video.author}}</a></li>
                    <li class="date">{{video.date}}</li>
                    
                    <li class="cat-links">
                        {% for category in post.category.all %}
                        <a href="{% url 'categories' category.id %}">{{category}}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div> <!-- end entry__header -->

            <div class="entry__content">

                <p class="lead drop-cap">
                    {{video.body|safe}}
                </p>

            </div> <!-- end entry content -->

            
        </article> <!-- end column large-full entry-->

        

        <div class="comments-wrap" style="width: 100%;  padding-left: 20px;
        padding-right: 20px;">

            <div id="comments" class="column large-12">

                <h3 class="h2">Comments</h3>

                <!-- START commentlist -->
                <ol class="commentlist">
                    {% for comment in video.video_comments.all %}
                    <li class="depth-1 comment" style="background-color: #eaeaea; padding: 10px 20px; margin: 5px auto;">

                        <div class="comment__content">

                            <div class="comment__info">
                                <div class="comment__author" style="text-transform: uppercase;">{{comment.name}}</div>

                                <div class="comment__meta">
                                    <div class="comment__time">{{comment.date}}</div>
                                </div>
                            </div>

                            <div class="comment__text">
                            <p>
                                {{comment.comment}}
                            </p>
                            </div>

                        </div>

                    </li> <!-- end comment level 1 -->
                    {% empty %}
                        <h2 style="text-align:center; color: brown;" >No Comments</h2>
                    {% endfor %}
                    

                </ol>
                <!-- END commentlist -->

            </div> <!-- end comments -->


            
            <div class="column large-12 comment-respond">

                <!-- START respond -->
                <div id="respond">
    
                    <h3 class="h2">Add Comment</h3>
    
                    <form name="contactForm" id="commentForm" method="post" action="" autocomplete="off">
                        {% csrf_token %}
                        {{ commentForm.media }}
                        {{ commentForm }}
                        <input type="submit" class="btn--primary full-width" value="Add Comment">
                    </form> <!-- end form -->
    
                </div>
                <!-- END respond-->
    
            </div> <!-- end comment-respond -->
    
        </div> <!-- end comments-wrap -->
    </main>

</div> <!-- end s-content -->


<script>
    var name = '{{video.id}}';
    document.getElementById('id_video').value = name;
</script>

{% endblock %}